- CHANGES.md
- src/Monad.hs
- universum.cabal
Previously it didn't work if containers of different types were invoked,
now it allows to e.g. traverse list and concat resulting d-lists.
> [SRK-2] Remake `concatMapM`

- src/Base.hs
This resolves #65.
You can exercise this by building against resolver=nightly. Current LTS is still on base-4.9.0.0
> Use TypeNats instead of TypeLits when possible

- .gitignore
- .travis.yml
- benchmark/Main.hs
- universum.cabal
I made benchmarks on lists where numbers are not greater than 100 (`"small"`) and where I have list consist of numbers from 1 to `n` repeated twice (`"big"`).
> Add benchmarks (#21)

- CHANGES.md
- src/Universum/Base.hs
- src/Universum/Exception.hs
- src/Universum/List/Reexport.hs
- universum.cabal
> [#100] Add bug

- CHANGES.md
- src/Universum/Exception.hs
- universum.cabal
Resolves #124 
Also specifies explicit lower bound for `ghc-prim` to keep backwards compatibility.
> [#124] Reexport more for Exception

- CHANGES.md
- src/Universum/Monad/Maybe.hs
> [#15] Add (?:) function

- CHANGES.md
- README.md
- src/Universum.hs
- src/Universum/Unsafe.hs
> [#135] Add documentation about internal module structure

- CHANGES.md
- src/Universum/Container/Class.hs
`ElementConstraint` gives some flexibility, but it doesn't seem it's needed. Having the `Eq (Element t)` constraint for the `elem` function looks like a sensible prerequisite -- I doubt people would define their own equality type classes and use them instead of `Eq`. And if `elem` requires something else than `Eq` (like `Hashable`), then this also should be required for constructing such data structure, so you can just constrain the entire instance like this:
```haskell
instance (Eq v, Hashable v) => Container (HashSet v) where
```
> Remove redundant 'ElementConstraint'

- CHANGES.md
`fmt` function is not a direct replacement for `pretty`. Its argument must be
'Builder', which is not the case for `pretty`.
I could not find a library with a direct replacement, so I only provide
possible definitions of `pretty` and `prettyL`.
> Fix CHANGES.md

- README.md
ChShersh/universum has been removed, so I moved the project into my account.
Hopefully later it will be moved into a company account. We have an issue
about it in our internal issue tracker (OPS-415).
> Update appveyor link

- CHANGES.md
- src/Universum/Base.hs
- src/Universum/Lifted/File.hs
So I read the heading of #186 and thought "hey, they should have `withFile`". Only after I started to implement it did I realize that discussion was already happening.
So I sort of accidentally already did the implementation.
This version currently exports `withFile` **and** `openFile` and `hClose`. And simply advises against using `openFile` and `hClose` in the documentation. Once we've settled the discussion of what should be exported this can be adjusted as needed.
> [#186] Implemented hClose and withFile

- CHANGES.md
- src/Universum/Debug.hs
For #204.
1. Make `trace` non-polymorphic over accepted text.
I don't see how could this be useful, taking into account that our string
literals and `show` are already polymorphic over text they produce.
2. Add `traceIdWith`.
> [#204] Improve traces

- CHANGES.md
- src/Universum/Print.hs
- src/Universum/Print/Internal.hs
- universum.cabal
I was rather surprised to find that Universum does not export a version of `hPutStrLn` and `hPutStr` etc.
This PR adds both `hPutStr` as well as `hPutStrLn` to `Universum.Print`. 
`putStr` as well as `putStrLn` are still available and exported from `Universum.Print`.
I decided, in the spirit of a smaller surface area and code of `Universum.Print`, to completely switch the `Print` class methods.
My logic was that this is a class people rarely implement themselves. (It may perhaps even be prudent not to export `hPutStrLn` and `hPutStr` as methods but as normal functions instead).
I am open for comments and improvement suggestions though.
```hs
class HPrint a where
hPutStrLn :: MonadIO m => Handle -> a -> m ()
hPutStr :: MonadIO m => Handle -> a -> m ()
class Print a where
putStr :: MonadIO …
```
> Added hPutStr and hPutStrLn to the Print module

- CHANGES.md
- src/Universum/Lifted/Env.hs
For some reason your lifted version of `die` is `m ()`, when it could be `m a`.
I skimmed through the issues and `CHANGES.md` but I could not find a reference as to why this was done, so I'm proposing to change it to a more general type. This is also the same type signature as the `exitWith` family as wenn as the `die` version in `base`.
Furthermore this, more general type signature is actually useful, particularly when handling erroneous user data.
> Generalize the type of `die`

- CHANGES.md
- src/Universum/Debug.hs
As we know, our `error` is funny:
```
*** Exception: 123
CallStack (from HasCallStack):
error, called at /home/martoon/serokell/universum/src/Universum/Debug.hs:62:11 in main:Universum.Debug
error, called at <interactive>:1:1 in interactive:Ghci1
```
I hope I fixed it to work as expected:
* Called from ghci:
```
λ> error "123"
*** Exception: 123
CallStack (from HasCallStack):
error, called at <interactive>:2:1 in interactive:Ghci1
```
* Called from code:
```
λ> meme
*** Exception: What meme?
CallStack (from HasCallStack):
error, called at /home/martoon/serokell/universum/src/Universum/Debug.hs:109:7 in main:Universum.Debug
```
No corresponding issue exist.
checkmark …
> Make `error` print callstack of its call site rather than its definition

- .hlint.yaml
- CHANGES.md
* Remove `-XTypeApplications`
* Remove various monad transformer combinators
* Remove `flipfoldl'`
* Remove `<<$>>`
https://issues.serokell.io/issue/SRK-119
This PR moves the updated Universum rules from the `serokell-util` repository to the `universum` repository, where they are easier to maintain.
- Tests
I checked whether I should update the docs and did so …
> [SRK-119] Update .hlint.yaml to version used in Ariadne

- CHANGES.md
- README.md
- benchmark/Main.hs
- src/Universum/String/Conversion.hs
- test/Test/Universum/Property.hs
- universum.cabal
Added rewrite rule to eliminate `toString . toText` conversions.
Benchmarks without rewrite rule:
```
benchmarked toText/toString
time                 1.013 ms   (875.1 μs .. 1.148 ms)
0.819 R²   (0.691 R² .. 0.904 R²)
mean                 1.621 ms   (1.268 ms .. 2.619 ms)
std dev              2.134 ms   (331.2 μs .. 4.071 ms)
variance introduced by outliers: 97% (severely inflated)
```
And with rewrite rule:
```
benchmarked toText/toString
time                 186.1 μs   (183.3 μs .. 188.4 μs)
0.998 R²   (0.996 R² .. 0.999 R²)
mean                 189.4 μs   (187.7 μs .. 191.8 μs)
std dev              7.508 μs   (5.823 μs .. 10.36 μs)
variance introduced by outliers: 20% (moderately inflated)
```
Fixed #212.
If something in this list is …
> Add rewrite rules for text conversion

- CHANGES.md
- src/Universum/Lifted/File.hs
There is a typo in referenced module names - there is no file related functions in `Data.Text` (correct module is `Data.Text.IO`). This PR fixes the issue. 
Issue could be observed here http://hackage.haskell.org/package/universum-1.5.0/docs/Universum-Lifted-File.html
and
messages start with identifiers of …
> Fix documentation in Universum.Lifted.File to mention correct module

- .travis.yml
- CHANGES.md
- CONTRIBUTING.md
- stack-8.8.1.yaml
- universum.cabal
Universum is not present in Stackage nightly resolver. The reason is that we have upper bound on `text` which does not work with `text` version in nightly. So here I bump this boundary and add explicit support for GHC-8.8.1.
Fixes #219.
- Tests
and
If necessary both of these can be …
> [#219] Support recent nightly

- CHANGES.md
- README.md
- src/Universum/Base.hs
- src/Universum/Container.hs
- src/Universum/Container/Class.hs
- src/Universum/List/Safe.hs
- src/Universum/Unsafe.hs
Get rid of unsafe `maximum`, `foldr1`, and similar functions.
Did it in the same way as done for `head`:
* `Container` typeclass now has `safeMinimum :: t -> Maybe (Element t)`.
* Additionally we provide `minimum :: NonEmpty a -> a`.
* Plus the original unsafe version put to `Unsafe` module.
One thing which worries me is that now one cannot simply write something like `foldr1 (+) [1..5]`. Constructing `NonEmpty` manually is not pleasant,`OverloadedLists` extension is rarely used because it would break many other function calls, e.g. `forM [1..5]`. Not sure which solution is best here.
Fixes #221.
checkmark indicating that you are sure it is dealt with (be that by …
> [#221] Safer maximum and stuff

- README.md
Problem: if you manually define `Show` instance and switch to
`Universum`, they will fail to compile. It's a gotcha we don't mention.
Solution: mention it in gotchas and the migration guide.
Resolves #221
- Tests
and
If necessary both of these can be achieved even after the commits have …
> [#221] Explain how to write Show instances

- CHANGES.md
- src/Universum/Monad/Trans.hs
Problem: Currently to lift a value `ma :: Maybe a` into `MaybeT m a`
you need to write `MaybeT (pure ma)`, which is bloating code with
unnecessary boilerplate.
Same idea applies for `Either e a` and `ExceptT e m a`.
`
Proposed solution:
Add functions `hoistMaybe :: Applicative m => Maybe a -> MaybeT m a` and
`hoistEither :: Applicative m => Either e a -> ExceptT e m a `
- Fixed #230
- Tests
silently …
> [#230] Add `hoistMaybe` and `hoistEither` functions

- .github/workflows/ci.yml
- CHANGES.md
- src/Universum/Applicative.hs
Motivation: `some` always returns a non-empty list, and it seems sane to
reflect that in types.
I do not replace the original `some` because we cannot insert new
`Alternative` typeclass into `Functor - Applicative - Monad` chain.
And hiding the original `some`, as I think, isn't worth the potential
confusion (when implementing Alternative instance and when just using
`some` I would need different `some`s). …
> Add `someNE`

- CHANGES.md
- src/Universum/Container/Class.hs
Problem: we lack a generic function for constructing an object from
list, while `toList` is present.
Solution: add `fromList`.
The sad point here is that we cannot define it opposite to `toList`
because for e.g. `Map` our `toList` returns only values, unfortunatelly.
(Maybe this is worth changing one day?)
So `fromList` is opposite to something intermediate between `toList` and
`toPairs`, and so I put it to a separate typeclass. …
> Add `FromList`

- .github/workflows/ci.yml
- README.md
- benchmark/Main.hs
- src/Universum/Nub.hs
- src/Universum/VarArg.hs
- stack.yaml
- stack.yaml.lock
- universum.cabal
Just some casual maintenance.
None
- Tests
and
If necessary both of these can be …
> [Chore] Update some versions

- CHANGES.md
- src/Universum/Lifted/Concurrent.hs
- universum.cabal
Problem: existing `modifyTVar'` is not pretty convenient. You need to
e.g. remember the order of arguments, and if several transformations
are required, composing them neatly may be difficult.
Solution: provide methods working with `State`, not a lambda. This way
one can write down modifications in do-block which is convenient.
Fixed #234 by adding the respective methods. 
- Tests
silently reappearing …
> [#234] Add concurrent primitives working with State

- CHANGES.md
- src/Universum/Exception.hs
`note` function from `Universum.Exception` is useless:
- `maybeToRight` is enough for most use cases
- it's specialized to `MonadError`, but in the wild there are also `MonadFail`, `MonadThrow`, `Either`, etc.
Deprecate `note`.
- Fixes #176 
- Tests
and
issue/pull request …
> [#176] Deprecate `note`

- CHANGES.md
- src/Universum/Monad/Reexport.hs
We export `listToMaybe` from `Data.Maybe`. It makes no sense
because we have `safeHead` in `Universum.Container` which does the same thing.
Remove `listToMaybe` from export list.
- Fixes #206
- Tests
and
issue/pull request and no reverted-my-earlier-commit changes) and …
> [#206] Remove `listToMaybe`

- .github/workflows/ci.yml
- CHANGES.md
- src/Universum/Monoid.hs
- src/Universum/VarArg.hs
- stack.yaml
- stack.yaml.lock
- universum.cabal
The primary goal of this PR is to make sure that `universum` can be built with GHC-9.2.2.
None
- Tests
and
**Example:** `[#42] …
> Support GHC-9.2.2

- CHANGES.md
- src/Universum.hs
- src/Universum/Function.hs
- src/Universum/Functor/Reexport.hs
Using `lens` library with `Universum` is uncomfortable
because some definitions start clashing (e.g. `Lens` or `(^.)`).
Deprecate these `microlens` and `microlens-mtl` dependencies.
- Fixes part of #182
- Tests
and
issue/pull request and no reverted-my-earlier-commit …
> [#182] Deprecate `microlens` and `microlens-mtl` dependencies

- CHANGES.md
- src/Universum/Base.hs
- src/Universum/Container/Class.hs
At this moment `concatMap` is exported from `Data.Foldable`
but we prefer using `Container` rather than `Foldable`.
Removed export of `concatMap` and made `concatMap` function
with type `concatMap :: Container c => (Element c -> [b]) -> c -> [b]`.
- Fixes #199
- Tests
and …
> [#199] `concatMap` type change

- test/Test/Universum/Issue208.hs
- universum.cabal
In `ghc-8.6.3` your code can produce `redundant constraint` warning
if you derive `Container` for newtype, but in `ghc-9.0.2` and newer
no warnings would be produced.
Added test, that should be compiled with `ghc-9.0.2` and newer
without warnings.
- Resolves #208
- Tests …
> [#208] `redundant constraint` test

- .github/workflows/ci.yml
- .xrefcheck.yaml
Problem: for some reason, running `curl -I
https://opensource.org/licenses/MIT` from within a GitHub Action's agent
returns a 503.
See: 
* https://github.com/serokell/universum/runs/7535914651?check_suite_focus=true
* https://github.com/serokell/universum/runs/7537865339?check_suite_focus=true
Solution: Temporarily disable this check.
None
- Tests
I checked …
> [Chore] Fix xrefcheck

- .hlint.yaml
Problem: our `.hlint.yaml` uses old syntax for rules that suggest / warn about operator usage, which produces parse errors if newest hlint-3.5 is used.
Solution: as in #277, we should move braces, e.g. use `(Control.Applicative.<|>)` instead of `Control.Applicative.(<|>)`
Fixed #277
- Tests
I checked whether I should update the …
> [#277] Use new syntax for operators in .hlint.yaml

- .hlint.yaml
Problem:
As in #277, some of our HLint rules have parenthesized lhs, e.g.
```
- warn: {lhs: (maybe pass f m), rhs: Universum.whenJust m f}
```
Such rules are triggering only on parnthisized code, e.g. rule above is not triggering on `x = maybe pass f m`.
Of course, we want to suggest `whenJust` in this case.
Solution:
Remove extra parenthesis in such rules, test this solves issue and is not leading to false reports.
Tested using HLint 3.5 (lastest) and 3.3.6
Fixed #279
I checked whether these changes impact the …
> [#279] Fix some HLint rules

- CHANGES.md
- benchmark/Main.hs
- src/Universum/String/Conversion.hs
- universum.cabal
Increase the version upper bound on `text` package.
The related logic (`pack`, `unpack`) seems to be untouched, and the rewrite rule speeds up a call of `toString . toText`.
Fixed #281 
- Tests
and
issue/pull request and no …
> [#281] Allow text-2.0

- README.md
- src/Universum/String/Conversion.hs
- test/Test/Universum/StringProps.hs
- universum.cabal
In the current `master` (after `2.0.1` version) `text` package changes implementation of `pack`, and this affects which rewrite rules should we use. After the new release, these and maybe some other changes will have to be applied.
Resolves #285
- Tests
- Record …
> [#285] Bump `text` package after 2.0.1 (to 2.0.2)

- .github/pull_request_template.md
- .github/workflows/ci.yml
- CHANGES.md
- src/Universum/Base.hs
- src/Universum/Container/Class.hs
- src/Universum/Monad/Container.hs
- src/Universum/String/Conversion.hs
- src/Universum/VarArg.hs
- stack.yaml
- stack.yaml.lock
- universum.cabal
We want to make universum work with the recent LTS-21.0, that would at least be helpful for Morley project.
So make CI test against the most recent GHC version, do the necessary changes.
The prepare the next release.
Related to #288
Fixed #
- Tests
- Record your …
> [Chore] Build with LTS-21.0, prepare a release

- .github/workflows/ci.yml
Problem: node16 is now deprecated and github-runner provided by nixpkgs
no longer supports this runtime. However, "actions/checkout@v3" uses
this runtime.
Solution: Update CI pipeline to use "actions/checkout@v4".
> [Chore] Update "actions/checkout"

- .github/workflows/ci.yml
- CHANGES.md
- README.md
- src/Universum/Debug.hs
- src/Universum/String/Conversion.hs
- src/Universum/TypeOps.hs
- stack.yaml
- stack.yaml.lock
- test/Test/Universum/StringProps.hs
- universum.cabal
Routine changes to support newer GHC versions.
None
- Tests
and
**Example:** `[#42] Short commit …
> [Chore] Update some dependencies, cleanup

- .github/workflows/ci.yml
- CHANGES.md
- README.md
- src/Universum/Container/Class.hs
- stack.yaml
- universum.cabal
Problem: there is ghc-9.10 for a while, but we don't support it for several reasons.
Solution:
1. Ignore foldl' import from Prelude in one module if GHC version is 9.10 or newer. This export was added to Prelude in base-4.20.
2. Add 9.10.1 to tested-with.
3. Update the CI config accordingly. 9.6 is still considered as the main version (as it's used in the latest LTS resolver), so we use it for 3 OS.
Resolves #296
I checked whether these changes impact the [`.hlint.yaml`](https://github.com/serokell/universum/tree/master/.hlint …
> [#296] Support ghc-9.10
