serokell/universum

- CHANGES.md
- src/TypeOps.hs
Now we can write `type MonadNyan = With [MonadIO, MonadReader nyan]`
> [SRK-2] Add `With` type operator

- CHANGES.md
- src/Conv.hs
> Fix an infinite loop

- CHANGES.md
- src/Exceptions.hs
- src/Monad/Trans.hs
- universum.cabal
See #62. I decided to make a PR right now, because it's quite small.
> Export exceptions-related functions from safe-exceptions

- CHANGES.md
- README.md
- src/Base.hs
- src/Bool.hs
- src/Containers.hs
- src/Exceptions.hs
- src/List.hs
- src/Monad.hs
- src/Monad/Either.hs
- src/Monad/Maybe.hs
- src/Monad/Trans.hs
- src/Universum.hs
- stack.yaml
- universum.cabal
This PR fixes most reexport issues. It's not complete. Issues I want to see resolved in this PR besides already finished: 
* #46 
* #47 
* #52
* #60 
Maybe #56 and #58.
> Resolve reexport issues and library improvements

- CHANGES.md
- README.md
- benchmark/Main.hs
- src/List.hs
- src/Nub.hs
- universum.cabal
Here is how `Nub` documentation looks like at the moment:
> Create `Nub` module (#68)

- CHANGES.md
- src/Print.hs
- src/String.hs
- src/Universum.hs
- universum.cabal
> [#83] Change types order in show and print

- CHANGES.md
- src/Universum.hs
- universum.cabal
> [#79] Import (<>) from Semogroup not Monoid

- .travis.yml
- CHANGES.md
- stack-8.2.2.yaml
- stack.yaml
- universum.cabal
Apply @Anton-Latukha  suggestions from `importify` settings.
> Improve travis settings

- CHANGES.md
- src/Container.hs
- src/Container/Class.hs
- src/Container/Reexport.hs
- src/Containers.hs
- src/Monad.hs
- src/Universum.hs
- universum.cabal
> [#80] rename containers to ToList and Container

- CHANGES.md
- README.md
- src/Universum/Container/Class.hs
> [#97] Add ToPairs class

- CHANGES.md
- src/Universum/Exception.hs
- universum.cabal
> [#114] Reexport more from safe-exceptions

- CHANGES.md
- src/Universum/Applicative.hs
- src/Universum/Base.hs
- src/Universum/Bool/Guard.hs
- src/Universum/Container/Class.hs
- src/Universum/Functor/Fmap.hs
- src/Universum/List/Safe.hs
- src/Universum/Monad/Container.hs
- src/Universum/Monad/Either.hs
- src/Universum/Monad/Maybe.hs
- src/Universum/Monoid.hs
- src/Universum/Nub.hs
- src/Universum/String/Conversion.hs
- src/Universum/VarArg.hs
- stack.yaml
- test/Doctest.hs
- universum.cabal
> [#53] Add doctest integration

- .travis.yml
- CHANGES.md
- Setup.hs
- stack-8.0.1.yaml
- stack-8.0.2.yaml
- universum.cabal
> [#117] Drop support of ghc 8.0.1

- README.md
- appveyor.yml
- test/Doctest.hs
- universum.cabal
Resolves #119 
This PR add very simple integration with AppVeyor CI.
> [#119] Add AppVeyor CI integration

- CHANGES.md
- src/Universum/Container/Reexport.hs
> [#104] Reexport hashWithSalt

- CHANGES.md
- src/Universum/Functor/Reexport.hs
> [#95] Reexport Compose

- CHANGES.md
- src/Exceptions.hs
- universum.cabal
@ChShersh I'd appreciate an upload of `universum-0.9.2` once you review/merge this.
> Backport safe-exceptions exports and 'bug'

- .travis.yml
- CHANGES.md
- src/Universum/String/Conversion.hs
- stack-nightly.yaml
- universum.cabal
> [#127] Fix doctest for text-1.2.3

- README.md
- shell.nix
- stack.yaml
- test/Spec.hs
- test/Test/Universum/Property.hs
- universum.cabal
Resolves https://github.com/serokell/universum/issues/36
Resolves https://github.com/serokell/universum/issues/99
> Added property tests with tasty and hedgehog, also a minor doc addition

- CHANGES.md
- README.md
- benchmark/Main.hs
- src/Universum/Container/Class.hs
- stack-7.10.3.yaml
- stack-8.0.2.yaml
- stack-nightly.yaml
- stack.yaml
- universum.cabal
> [#136] Return type of foldl' back, add flipfoldl'

- CHANGES.md
- README.md
- src/Universum/Function.hs
> [#129] Reexport id

- CHANGES.md
- README.md
- src/Universum/Unsafe.hs
- universum.cabal
> [#128] Add Unsafe module

- CHANGES.md
- src/Universum/Base.hs
- src/Universum/Container/Class.hs
- src/Universum/Exception.hs
- universum.cabal
Resolves #130 
Resolves #118 
Resolves #60 
Resolves #144
> [#130] Merge 'ToList' and 'Container', [#118] Export 'Type'

- .hlint.yaml
- CHANGES.md
- src/Universum/Container/Class.hs
- src/Universum/List/Reexport.hs
- src/Universum/List/Safe.hs
- src/Universum/Monoid.hs
I have already checked it on one private repositories and it seems to be working
Resolves #98
> [#98] Add universum specific hlint.yaml

- benchmark/Main.hs
- stack-7.10.3.yaml
- universum.cabal
> [#152] Use gauge instead of criterion, clean dependencies

- src/Universum/Debug.hs
I just tried building universum with ghc-8.4.1 to check https://github.com/haskell/haddock/issues/765 and this is the only change I had to make in order to make things compile.
> Compat wit ghc-8.4.1-rc1

- README.md
Also enhanced documentation in several places.
Resolves #44
> [#44] Add migration guide from Prelude

- CHANGES.md
- README.md
- src/Universum/Bool/Guard.hs
- src/Universum/Bool/Reexport.hs
- src/Universum/Container/Class.hs
- src/Universum/DeepSeq.hs
- src/Universum/Function.hs
- src/Universum/Functor/Fmap.hs
- src/Universum/Functor/Reexport.hs
- src/Universum/Lifted/ST.hs
- src/Universum/List/Reexport.hs
- src/Universum/List/Safe.hs
- src/Universum/Monad/Container.hs
- src/Universum/Monad/Maybe.hs
- src/Universum/Monad/Reexport.hs
- src/Universum/Monoid.hs
- src/Universum/String/Conversion.hs
- src/Universum/String/Reexport.hs
- src/Universum/VarArg.hs
- stack.yaml
- universum.cabal
> [#73] Add 100% Haddock coverage + more examples

- CHANGES.md
- CODEOWNERS
- CONTRIBUTING.md
- universum.cabal
> [#148] Add CODEOWNERS and contributing guide

- .hlint.yaml
- CHANGES.md
- src/Universum/Container/Class.hs
- src/Universum/Exception.hs
- src/Universum/Function.hs
- src/Universum/Lifted/Env.hs
- src/Universum/Lifted/File.hs
- src/Universum/Lifted/ST.hs
- src/Universum/List/Safe.hs
- src/Universum/Nub.hs
- src/Universum/TypeOps.hs
- universum.cabal
> Some fixes for 1.3.0

- CHANGES.md
- universum.cabal
Update version to 1.5.0 to release it.
None.
- Tests
and
If necessary both of these …
> Update version to 1.5.0

- CHANGES.md
- universum.cabal
We want to release newer version.
No issue, just chore.
- Tests
and
> Update version to 1.6.0

- .travis.yml
- CHANGES.md
- appveyor.yml
- benchmark/Main.hs
- src/Universum/Base.hs
- src/Universum/Container/Class.hs
- src/Universum/Debug.hs
- src/Universum/Exception.hs
- src/Universum/Lifted/File.hs
- src/Universum/List/Reexport.hs
- src/Universum/List/Safe.hs
- src/Universum/Monad/Reexport.hs
- src/Universum/Monoid.hs
- src/Universum/Nub.hs
- src/Universum/TypeOps.hs
- stack-8.0.2.yaml
- test/Doctest.hs
- test/Spec.hs
- universum.cabal
Here I enable all warnings that I find sane, enable `-Werror` and fix new warnings.
Fixed #185.
- Tests
and
**Example:** `[#42] …
> [#185] Enable more warnings and fix them

- .github/workflows/ci.yml
- CHANGES.md
- README.md
- universum.cabal
Use the [xrefcheck](https://github.com/serokell/xrefcheck/) tool to ensure that cross-references are valid.
None
- Tests
and …
> Add xrefcheck

- universum.cabal
Problem: we want to release 1.7.1 version.
Solution: update it in universum.cabal.
None
- Tests
and
**Example:** `[#42] Short …
> Update package version

- CHANGES.md
- src/Universum/Container/Class.hs
Problem: there are no `ToPairs` instances for `[(k, v)]` and `NonEmpty (k, v)`
Resolves #244 
- Tests
and
**Example:** `[#42] Short …
> [#244] Added two new instances for ToPairs

- CHANGES.md
- src/Universum/String/Conversion.hs
- src/Universum/String/Reexport.hs
`readMaybe` type isn't polymorphic.
One of the key points in the design of `Universum` is to avoid `String` as much as possible.
Changed type to `readMaybe :: (ToString a, Read b) => a -> Maybe b`
- Fixes #165
- Tests
and
issue/pull request and no reverted-my-earlier-commit …
> [#165] `readMaybe` type changing

- CHANGES.md
- universum.cabal
This PR bumps up the library version to 1.8.0 and updates the changelog.
None
- Tests
and
**Example:** `[#42] Short commit …
> [Chore] Prepare 1.8.0 release

- .github/workflows/ci.yml
- .xrefcheck.yaml
Update GitHub actions.
None
- Tests
and
If necessary …
> [Chore] Update GitHub actions

- README.md
Universum is now available in Stackage Nightly after a break.
Resolves #288
Fixed #288
- Tests
and …
> [#288] Re-enable Stackage Nightly badge

- .github/workflows/ci.yml
- .xrefcheck.yaml
- README.md
* Update `ci.yml` to use `xrefcheck-0.3.1`
* Update `.xrefcheck.yaml` to use the new config format.
* Remove a problematic link from the README.md
> [Chore] Update to xrefcheck-0.3.1

- .github/workflows/ci.yml
- CHANGES.md
- src/Universum/String/Conversion.hs
- stack.yaml
- universum.cabal
Update some versions and such.
None
- Tests
and
If …
> [Chore] A round of maintenance
